### PR TITLE
Added a way to start the dialog box from script

### PR DESCRIPTION
**Pull request by I-Have-No-Idea-What-IAmDoing**
You can now restart and reuse the same syndibox node

also added a way to stop and reset the node too

also got rid of a debug print from last pull request

still a draft as i need to add documentation and fix a few problems first but i wanted to get it out here to make sure it looks right, right now

### CODE REVIEW

**Comment by Sudospective** [comment]
oops i did not mean to mark as ready for review

**Review by Sudospective — CHANGES_REQUESTED** [review]
So far it looks good, I'll wait until you mark as ready yourself and review it once more.

**Comment by I-Have-No-Idea-What-IAmDoing** [comment]
It should be ready to review for now, i added some comments and i also fixed a issue with transposing

**Comment by I-Have-No-Idea-What-IAmDoing** [comment]
Just also fixed 2 crash issue relating to hiding text (though it still does not work) and alternate fonts

**Review by Sudospective — APPROVED** [review]
Thanks, this is a big help with ease-of-use

**Pull request merged**
